### ISSUE TITLE
don't fail if profiler already initialized

### ISSUE THREAD

**Issue by michael-kenzel** [AnyDSL/anyq#2]
Instrumentation calls `cuptiProfilerInitialize` to enable higher precision GPU timestamps. However, we currently fail if the profiler was already initialized, which prevents running with nvprof. We should fix this by not failing if `cuptiProfilerInitialize` fails due to the profiler already having been initialized.

**Comment by richardmembarth** [comment]
This fails also on my machine without running `nvprof`.
Just running any CUDA binary fails with error code 15: `CUPTI_ERROR_NOT_INITIALIZED`

**Comment by richardmembarth** [comment]
Maybe, we should check for this error code and continue without CUPTI.
> CUPTI calls will fail with error code CUPTI_ERROR_NOT_INITIALIZED if the CUDA driver version is not compatible with the CUPTI version.

https://docs.nvidia.com/cupti/r_main.html
